Donation/Project/Models/Donation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Models
{
    public class Donation
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "กรุณาใส่ชื่อสิ่งของที่จะบริจาค")]
        [DataType(DataType.Text)]
        [Display(Name = "ชื่อสิ่งของ")]
        public string Title { get; set; }
        [Required(ErrorMessage = "กรุณาใส่ประเภทสิ่งของที่จะบริจาค")]
        [DataType(DataType.Text)]
        [Display(Name = "ประเภทสิ่งของ")]
        public string Type { get; set; }

        [Required(ErrorMessage = "กรุณาใส่จำนวนสิ่งของ")]
        [Range(0, 1000)]
        [Display(Name = "จำนวน")]
        public decimal Number { get; set; }

        [Required(ErrorMessage = "กรุณาใส่วันที่จะบริจาค")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "วันที่")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "กรุณาใส่ชื่อผู้บริจาค")]
        [DataType(DataType.Text)]
        [Display(Name = "ชื่อหลัก")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "กรุณาใส่นามสกุลผู้บริจาค")]
        [DataType(DataType.Text)]
        [Display(Name = "นามสกุล")]
        public string Lname { get; set; }

        [Required(ErrorMessage = "กรุณาใส่เบอร์โทรศัพท์ติดต่อ")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "เบอร์โทรศัพท์ติดต่อ")]
        public string Phone { get; set; }

        [DataType(DataType.Url)]
        [Display(Name = "เฟซบุ๊ค")]
        public string Facebook { get; set; }

    }
    
}

Donation/Project/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using PagedList;
using PagedList.Mvc;


namespace Project.Controllers
{
    public class DonationsController : Controller
    {
        private DonationContext db = new DonationContext();

        // GET: Donations
        /*public ActionResult Index()
        {
            return View(db.Donations.ToList());
        }*/

        public ActionResult Index(string donationType, string searchString, string nameItem, int? page)
        {
            var MajorLst = new List<string>();
            var MajorQry = from d in db.Donations orderby d.Type select d.Type;
            MajorLst.AddRange(MajorQry.Distinct());
            ViewBag.donationType = new SelectList(MajorLst);

   

            var donation = from m in db.Donations select m;
            if (!string.IsNullOrEmpty(searchString))
            {
                donation = donation.Where(s => s.Title.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(donationType))
            {
                donation = donation.Where(x => x.Type == donationType);
            }
            if (!string.IsNullOrEmpty(nameItem))
            {
                donation = donation.Where(x => x.Title == nameItem);
            }

            return View(donation.ToList().ToPagedList(page ?? 1, 3));
        }

        [HttpPost]
        public string Index(FormCollection fc, string searchString)
        {
            return "<h3> From [HttpPost]Index: " + searchString + "</h3>";
        }

        // GET: Donations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donation donation = db.Donations.Find(id);
            if (donation == null)
            {
                return HttpNotFound();
            }
            return View(donation);
        }

        // GET: Donations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Donations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Type,Number,Date,Fname,Lname,Phone,Facebook")] Donation donation)
        {
            if (ModelState.IsValid)
            {
                db.Donations.Add(donation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(donation);
        }

        // GET: Donations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donation donation = db.Donations.Find(id);
            if (donation == null)
            {
                return HttpNotFound();
            }
            return View(donation);
        }

        // POST: Donations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Type,Number,Date,Fname,Lname,Phone,Facebook")] Donation donation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donation);
        }

        // GET: Donations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donation donation = db.Donations.Find(id);
            if (donation == null)
            {
                return HttpNotFound();
            }
            return View(donation);
        }

        // POST: Donations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donation donation = db.Donations.Find(id);
            db.Donations.Remove(donation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Views(string donationType, string searchString, int? page)
        {
            var MajorLst = new List<string>();
            var MajorQry = from d in db.Donations orderby d.Type select d.Type;
            MajorLst.AddRange(MajorQry.Distinct());
            ViewBag.donationType = new SelectList(MajorLst);

            var donation = from m in db.Donations select m;
            if (!string.IsNullOrEmpty(searchString))
            {
                donation = donation.Where(s => s.Title.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(donationType))
            {
                donation = donation.Where(x => x.Type == donationType);
            }
            return View(donation.ToList().ToPagedList(page ?? 1, 5));
        }
    }
}

Donation/Project/Views/Donations/Create.cshtml
@model Project.Models.Donation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Donation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-controls" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Facebook, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Facebook, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Facebook, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Donation/Project/Views/Donations/Delete.cshtml
@model Project.Models.Donation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Donation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Facebook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Facebook)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Donation/Project/Views/Donations/Details.cshtml
@model Project.Models.Donation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Donation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Facebook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Facebook)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Donation/Project/Views/Donations/Edit.cshtml
@model Project.Models.Donation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Donation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Facebook, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Facebook, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Facebook, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Donation/Project/Views/Donations/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Project.Models.Donation>

@using PagedList.Mvc;
@{
    ViewBag.Title = "Donation";
}

<h1>Donation</h1>
<p>
    <h2>
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; กด create new เพื่อเพิ่มรายละเอียดสิ่งของที่ได้รับบริจาค
    </h2>
</p>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Donations", FormMethod.Get))
{
    <p>
        Type: @Html.DropDownList("donationType", "All")
        Title: @Html.TextBox("searchString")
        <!--<br />-->
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            ลำดับที่
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Facebook)
        </th>
        <th>
            Rank
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Facebook)
            </td>
            <td>
                @Model.Count(x => x.Fname == item.Fname && x.Lname == item.Lname)
            </td>
            <td>
                <button type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                </button><br />
                <button type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-file" aria-hidden="true"></span> @Html.ActionLink("Details", "Details", new { id = item.ID })
                </button><br />
                <button type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </button>
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    searchBy = Request.QueryString["searchBy"],
    search = Request.QueryString["search"]
}),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayItemSliceAndTotal = true })

Donation/Project/Views/Donations/Views.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Project.Models.Donation>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Home";
}

<p><h1>บริจาคสิ่งของ</h1></p>
<p>
    <h2>
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; หากท่านมีสิ่งของเก่าแต่ยังใช้การได้ดี หรือไม่ใช้แล้ว เช่น เสื้อผ้า เครื่องนุ่งห่ม หนังสือ เครื่องเรียน อุปกรณ์กีฬา คอมพิวเตอร์ ของใช้ต่างๆ
    </h2>
</p>
<p>
    <h2>
        ที่ยังอยู่ในสภาพใช้การได้ดี ท่านสามารถบริจาคสิ่งของเหล่านั้น ไปยังผู้ขาดแคลนด้อยโอกาสที่มีความต้องการใช้งานผ่านทางเว็บไซต์ของเราได้
    </h2>
</p>
<p>
    <h2>
        และสำหรับผู้ที่ขาดแคลน สามารถดูรายการสิ่งของ เพื่อขอรับบริจาคได้ทางเว็บไซต์นี้
    </h2>
</p>
<p>
    <h2>
        <font color="red">
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; *** ติดต่อบริจาคและรับสิ่งของได้ที่ ใต้หอพักชาย ตั้งแต่่เวลา 09.00 - 17.00 น. หรือติดต่อ นาย จิรายุ ชิณวงศ์ โทร. 095-0193878
        </font>
    </h2>
</p>
<br />
@using (Html.BeginForm("Index", "Donations", FormMethod.Get))
{
    <p>
        Type: @Html.DropDownList("donationType", "All")
        Title: @Html.TextBox("searchString")
        <!--<br />-->
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            ลำดับที่
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Facebook)
        </th>
        <th>
            สถานะ
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Facebook)
            </td>
            <td>
                @if(item.Number > 0)
                {
                    <p><font color="green">สามารถจองได้</font></p>
                }
                else
                {
                    <p><font color="red">ไม่สามารถจองได้</font></p>
                }
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("Views", new
{
    page,
    searchBy = Request.QueryString["searchBy"],
    search = Request.QueryString["search"]
}),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayItemSliceAndTotal = true })